// @ts-ignore
/// <reference types="react-native-css/types" />

// NOTE: This file should not be edited and should be committed with your source code. It is generated by react-native-css. If you need to move or disable this file, please see the documentation.

// Temporary module declarations to silence missing type errors for nativewind preview version.
// When nativewind publishes proper types for the used version, remove these.
declare module 'nativewind' {
  export interface UseColorSchemeResult {
    colorScheme: 'light' | 'dark' | 'system';
    setColorScheme: (value: 'light' | 'dark' | 'system') => void;
    toggleColorScheme: () => void;
  }
  export function useColorScheme(): UseColorSchemeResult;
}
